apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: g6pg2atqa-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: g6pg2atqa-go 
  name: g6pg2atqa-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: g6pg2atqa-go 
